title: Shulhin D. 
email: #test@gmail.com
description: free-thinker, coder, warhammer fan.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dz-s
linkedin_username: dshulgin2015
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
gems: ["jemoji"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
